// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU13n3cGWfR7BA3uK7AkvwgLqWgY_4qxU',
    appId: '1:391246139085:android:f51d4de07157f270116384',
    messagingSenderId: '391246139085',
    projectId: 'hauxinh0411-69b89',
    storageBucket: 'hauxinh0411-69b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEYWuit8ZUX1cgOQ7UEWS8FUZAA4BOvy0',
    appId: '1:391246139085:ios:da07f8407c20658e116384',
    messagingSenderId: '391246139085',
    projectId: 'hauxinh0411-69b89',
    storageBucket: 'hauxinh0411-69b89.appspot.com',
    androidClientId: '391246139085-j88b3m3nva8m49tps4r6jqdb1sefg2a8.apps.googleusercontent.com',
    iosClientId: '391246139085-76048k2l8vjfpb0qb6a47cd0vssoo6dh.apps.googleusercontent.com',
    iosBundleId: 'com.duclh11.hauxinh',
  );
}
